# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
lang: ja
title: マイ没日録
author: プレハブ小屋
email: yojyo@hotmail.com
description: このブログは私にとって門外不出の真実の日記でなければならない。
baseurl: /sunset
url: https://showa-yojyo.github.io
repository: https://github.com/showa-yojyo/sunset

show_excerpts: true

header_pages:
  - about.md
  - archive.html

twitter_username: showa_yojyo
github_username: showa-yojyo
rss: RSS

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
theme: minima
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - .gitignore
  - .mailmap

# Minima settings
minima:
  date_format: "%Y-%m-%d (%a)"

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      author: "showa-yojyo"
      categories:
        - diary
      layout: diary
      image:
        path: /assets/images/ogp-default.png
        width: 400
        height: 400
  - scope:
      path: archive
      type: pages
    values:
      layout: archive
